### ISSUE TITLE
How to handle "VACANT" properties

### ISSUE THREAD

**Issue by carrieklc** [UBC-MDS/Vancouver-Property-Value-Analysis#10]
@ian-flores 
I noticed there are records in the property value dataset whose street address is listed as "VACANT" - some of these are also missing postal codes, although they can have current land/improvement values and neighbourhood codes filled in. How should we handle these cases? Remove them all, keep, or only keep ones with non-null codes & values? 

There are ~2600 cases like this (for residential property records).

**Comment by ian-flores** [comment]
I think we can use them because we are using the neighbourhood codes to do the joins. But what do you think?

**Comment by carrieklc** [comment]
Yes, I think as long as they have neighbourhood codes. I've left them in as part of the code cleaning for now.
