### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by rachelkriggs** [UBC-MDS/Vancouver-Property-Value-Analysis#18]
- move relevant drop-down box (neighborhood) to the bottom with the other drop-down box.

- add a text blurb defining the affordability gap so that the user understands right away what they are looking at / exploring

- set UBC to NA as a visual indicator that data is missing (include it in the map)

- don't allow selection of both median and average; also don't allow selection of neither; one or the other

- for selection of age variable, repeat text on right graph

- use color to highlight the top two tabs (Home and Individual Level of Data) and / or place them on the white space

- text size on plots is a bit too small

**Comment by carrieklc** [comment]
Thank you for your feedback, Rachel. In response to your suggestions, in Milestone 3, we have made the following changes:
- Placed both relevant dropdown selections (neighbourhood, SES variable) right on top of the bar plot they filter
- Added a definition of "affordability gap" in the context of our app
- Increased text size of title and axes labels in plot 

With regards to UBC, upon further research, we realized it is not considered a "local area" or neighbourhood of Vancouver. This explains why the Vancouver Census data did not include data for UBC.
