### ISSUE TITLE
🙌 peer-feedback 📢

### ISSUE THREAD

**Issue by jessimk** [UBC-MDS/Vancouver-Property-Value-Analysis#19]
Great app folks!

This is such an important and timely topic! It's nice to have a tool to explore the issue of affordability in Vancouver 🙌

Overall, the colours and fonts are clean easy to look at. The map tiling looks awesome and it's nice to be able to explore neighbourhoods around the city in terms the variables you've chosen ( income, property values, age etc).

Here is some more feedback: 

- The first dropdown in the sidebar could be positioned next to the plots that it modifies
- When I loaded the app, I didn't see the bar plots below so I didn't know there was more to the app and I didn't know what the first dropdown modified. Maybe change plot size or add an arrow that indicates that there's more info below.
- When I loaded the app, the map background didn't show up-- I only saw abstract tiles. In turn, I didn't initially understand why the map had a zoom function.
- When the map loads, only 1/3 of the map represents Vancouver. The other thirds are water+UBC and Burnaby. You could probably crop this in a way so that the prime real estate (no pun intended) on the top of your  app's "landing page" is used in a more informative way.
- I'd love more info somewhere detailing what the 'affordability gap' measure means// how it was derived. I'd also love more info on where you got your data etc. Some guiding questions about what we should be thinking about would be nice, perhaps as plot titles but this last piece is not necessary given your users, (as defined in your use case) are government bureaucrats.  
- Strathcona, in one of your map views has an NA value :( ... why?
- I'm not super sure how much map/background detail you need in terms of roads etc for zooming in and out of but if you accidentally end up in PoCo or other municipalities... you see some green shading and it could be confusing ("is that green part of your legend?".. etc.).
- The legend could be made more readable as there are a lot of zeros. Maybe instead of 1,000,000 it could be 1M ? But honestly, it's also fine the way it is.

Overall-- very cool project and very cool app!

**Comment by carrieklc** [comment]
Hi Jess, thank you for your feedback!  In response to your suggestions, in Milestone 3, we have made the following changes:

- Added a definition of "affordability gap" in the context of our app
- Placed both relevant dropdown selections (neighbourhood, SES variable) right on top of the bar plot they modify
- Moved barplot to the right half of the app so they are less easily missed
- Fixed the map so more of the "screen real estate" is fixed on Vancouver
- Reduced the amount of detail shown on the map to try to strike a better balance in how much background detail to show
