### ISSUE TITLE
Using shinythemes instead of bare Shiny

### ISSUE THREAD

**Issue by ian-flores** [UBC-MDS/Vancouver-Property-Value-Analysis#6]
When implementing the UI, let's use `shinythemes` to have a better looking UI than just the default. 

Link to the package website: https://rstudio.github.io/shinythemes/

**Comment by carrieklc** [comment]
Sure, sounds good - the theme you picked in 68fa658f10803dd9ff155ff631708f7318c6c82d looks pretty slick.

**Comment by ian-flores** [comment]
Nice!
