### ISSUE TITLE
Work to be done

### ISSUE THREAD

**Issue by ian-flores** [UBC-MDS/Vancouver-Property-Value-Analysis#9]
Ian:
- Maps Visualisations

Carrie:
- Plot Visualisations
- Finish the neighbourhood mapping

**Comment by carrieklc** [comment]
* Neighbourhood mapping - completed
* Plot Visualizations - initial draft completed but will explore overlaying Vancouver & neighbourhood distribution plots, per Kate's suggestion.

**Still To Do:** @ian-flores 
* Develop a code of conduct - submitted PR including this
* Deploy Shiny app to shinyapps.io
* Write report documenting functionality of app in a markdown document, including screenshots

**Comment by ian-flores** [comment]
Do you prefer to do the deployment or the report? I think it's kind of hard to split those tasks. I can volunteer for the deployment if you want.

**Comment by ian-flores** [comment]
Also, I already have the income map fully functional

**Comment by carrieklc** [comment]
Ok, I can take on the report.

**Comment by carrieklc** [comment]
Completed tasks - will close ticket.
